### ISSUE TITLE
Import WireGuard Correctly, Not Directly in Tree

### ISSUE THREAD

**Issue by zx2c4** [halogenOS/android_kernel_oneplus_msm8998#1]
Some recent *important* WireGuard changes I thought I should tell you about here.

You've been building WireGuard as part of this kernel by actually committing the WireGuard source code. *Please stop doing this*, and instead move over to the new method, which was created in response to a few recent requests and concerns. It's also an *important* thing to do, because it ensures that things actually stay up to date. [The below instructions follow from "Standalone Kernel Built-in Module" in the documentation.](https://git.zx2c4.com/android_kernel_wireguard/about/)

First remove what you did before:

```
$ rm -rf path/to/kernel/net/wireguard # or just revert your previous commit
```

Now run the persistent patcher script and commit its results:

```
$ cd /tmp && git clone https://git.zx2c4.com/android_kernel_wireguard/
$ cd android_kernel_wireguard/standalone-kernel
$ ./patch-kernel.sh path/to/kernel
$ cd /tmp && rm -rf android_kernel_wireguard
$ cd path/to/kernel && git add . && git commit -a -m "net/wireguard: add to tree via updater mechanism"
```

That should be all that's required. It's very important that it gets done. Please let me know if you have any issues.

**Comment by msfjarvis** [comment]
Simao taking the lazy way out as usual. I'll fix this up immediately, thanks for looking out!

**Comment by xdevs23** [comment]
I did not even know about WireGuard, what's happening here?

**Comment by msfjarvis** [comment]
You're behind upstream (Nathan's kernel)

**Comment by xdevs23** [comment]
Hmm yeah but don't bother about the kernel because it's not working right now anyway
